### ISSUE TITLE
Hey - does this repo work?

### ISSUE THREAD

**Issue by aduriseti** [FireController1847/pandora-radio-desktop#1]
Looking for a node or python shim around the pandora api.

You have any experience w/ the implementations provided here: https://6xq.net/pandora-apidoc/implementations/

**Comment by FireController1847** [comment]
Yes. It does! Although we do not have many of the APIs implemented, we do have the basics. Since I never really have the free time to work on this much anymore I haven't been able to add many commits or new features, but it is in development just very very very slowly. Any new PRs to fix bugs or add features are strongly appreciated!

**Comment by aduriseti** [comment]
Oh nice - I'll take a look - wouldn't have thought such a lightweight shim was possible.

**Comment by FireController1847** [comment]
I tried my best to find APIs that did what I needed without any bull that I didn't, so imo it did turn out well.

**Comment by FireController1847** [comment]
Oh wait, I think I may have mistaken this repository for https://github.com/FireController1847/Pandora.js, and I think you may have too. This repository is currently _not_ updated, but the one I just linked I think is what you're looking for.

**Comment by aduriseti** [comment]
Oh whoops - yeah guess I had the wrong tab open - my bad.
